import { SeedQuestionInput } from "./seed-helpers";

const baseQuestions: SeedQuestionInput[] = [
  {
    title: "Two Sum",
    slug: "two-sum",
    description: "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.",
    difficulty: "EASY",
    tags: ["array", "hash-map"],
    starterCode: {
      python: "def two_sum(nums, target):\n    # TODO\n    return []\n",
      javascript: "function twoSum(nums, target) {\n  // TODO\n  return [];\n}\n",
      java: "class Solution {\n    public int[] twoSum(int[] nums, int target) {\n        // TODO\n        return new int[0];\n    }\n}\n",
    },
    visibleTests: [
      { input: "nums=[2,7,11,15], target=9", expected: "[0,1]" },
      { input: "nums=[3,2,4], target=6", expected: "[1,2]" },
      { input: "nums=[3,3], target=6", expected: "[0,1]" },
    ],
    hiddenTests: [
      { input: "nums=[1,5,5,11], target=10", expected: "[1,2]" },
      { input: "nums=[0,4,3,0], target=0", expected: "[0,3]" },
      { input: "nums=[-1,-2,-3,-4,-5], target=-8", expected: "[2,4]" },
      { input: "nums=[9,10,11,12], target=21", expected: "[0,2]" },
      { input: "nums=[1,2], target=3", expected: "[0,1]" },
    ],
    optimalBigO: "O(n)",
    optimalSpace: "O(n)",
  },
  {
    title: "Valid Anagram",
    slug: "valid-anagram",
    description: "Return true if t is an anagram of s.",
    difficulty: "EASY",
    tags: ["string", "hash-map"],
    starterCode: {
      python: "def is_anagram(s, t):\n    # TODO\n    return False\n",
      javascript: "function isAnagram(s, t) {\n  // TODO\n  return false;\n}\n",
      java: "class Solution {\n    public boolean isAnagram(String s, String t) {\n        // TODO\n        return false;\n    }\n}\n",
    },
    visibleTests: [
      { input: "s=anagram, t=nagaram", expected: "true" },
      { input: "s=rat, t=car", expected: "false" },
      { input: "s=aacc, t=ccac", expected: "false" },
    ],
    hiddenTests: [
      { input: "s=, t=", expected: "true" },
      { input: "s=ab, t=ba", expected: "true" },
      { input: "s=ab, t=abc", expected: "false" },
      { input: "s=Listen, t=Silent", expected: "false" },
      { input: "s=aaab, t=abaa", expected: "true" },
    ],
    optimalBigO: "O(n)",
    optimalSpace: "O(1)",
  },
  {
    title: "Palindrome Number",
    slug: "palindrome-number",
    description: "Determine if an integer is a palindrome without converting to a string.",
    difficulty: "EASY",
    tags: ["math"],
    starterCode: {
      python: "def is_palindrome(x):\n    # TODO\n    return False\n",
      javascript: "function isPalindrome(x) {\n  // TODO\n  return false;\n}\n",
      java: "class Solution {\n    public boolean isPalindrome(int x) {\n        // TODO\n        return false;\n    }\n}\n",
    },
    visibleTests: [
      { input: "x=121", expected: "true" },
      { input: "x=-121", expected: "false" },
      { input: "x=10", expected: "false" },
    ],
    hiddenTests: [
      { input: "x=0", expected: "true" },
      { input: "x=12321", expected: "true" },
      { input: "x=1234321", expected: "true" },
      { input: "x=1231", expected: "false" },
      { input: "x=1000021", expected: "false" },
    ],
    optimalBigO: "O(log n)",
    optimalSpace: "O(1)",
  },
  {
    title: "Roman to Integer",
    slug: "roman-to-integer",
    description: "Convert a Roman numeral to an integer.",
    difficulty: "EASY",
    tags: ["string", "math"],
    starterCode: {
      python: "def roman_to_int(s):\n    # TODO\n    return 0\n",
      javascript: "function romanToInt(s) {\n  // TODO\n  return 0;\n}\n",
      java: "class Solution {\n    public int romanToInt(String s) {\n        // TODO\n        return 0;\n    }\n}\n",
    },
    visibleTests: [
      { input: "s=III", expected: "3" },
      { input: "s=LVIII", expected: "58" },
      { input: "s=MCMXCIV", expected: "1994" },
    ],
    hiddenTests: [
      { input: "s=IV", expected: "4" },
      { input: "s=IX", expected: "9" },
      { input: "s=XL", expected: "40" },
      { input: "s=CM", expected: "900" },
      { input: "s=MMXX", expected: "2020" },
    ],
    optimalBigO: "O(n)",
    optimalSpace: "O(1)",
  },
  {
    title: "Longest Common Prefix",
    slug: "longest-common-prefix",
    description: "Find the longest common prefix string amongst an array of strings.",
    difficulty: "EASY",
    tags: ["string"],
    starterCode: {
      python: "def longest_common_prefix(strs):\n    # TODO\n    return \"\"\n",
      javascript: "function longestCommonPrefix(strs) {\n  // TODO\n  return \"\";\n}\n",
      java: "class Solution {\n    public String longestCommonPrefix(String[] strs) {\n        // TODO\n        return \"\";\n    }\n}\n",
    },
    visibleTests: [
      { input: "strs=[flower, flow, flight]", expected: "fl" },
      { input: "strs=[dog, racecar, car]", expected: "" },
      { input: "strs=[interview, interrupt, internal]", expected: "int" },
    ],
    hiddenTests: [
      { input: "strs=[a]", expected: "a" },
      { input: "strs=[ab, a]", expected: "a" },
      { input: "strs=[prefix, pre, prevent]", expected: "pre" },
      { input: "strs=[, ]", expected: "" },
      { input: "strs=[same, same, same]", expected: "same" },
    ],
    optimalBigO: "O(n * m)",
    optimalSpace: "O(1)",
  },
  {
    title: "Merge Two Sorted Lists",
    slug: "merge-two-sorted-lists",
    description: "Merge two sorted linked lists and return it as a new sorted list.",
    difficulty: "EASY",
    tags: ["linked-list", "two-pointers"],
    starterCode: {
      python: "class ListNode:\n    def __init__(self, val=0, next=None):\n        self.val = val\n        self.next = next\n\n\ndef merge_two_lists(l1, l2):\n    # TODO\n    return l1\n",
      javascript: "function mergeTwoLists(l1, l2) {\n  // TODO\n  return l1;\n}\n",
      java: "class ListNode { int val; ListNode next; ListNode(int x) { val = x; } }\nclass Solution {\n    public ListNode mergeTwoLists(ListNode l1, ListNode l2) {\n        // TODO\n        return l1;\n    }\n}\n",
    },
    visibleTests: [
      { input: "l1=[1,2,4], l2=[1,3,4]", expected: "[1,1,2,3,4,4]" },
      { input: "l1=[], l2=[]", expected: "[]" },
      { input: "l1=[], l2=[0]", expected: "[0]" },
    ],
    hiddenTests: [
      { input: "l1=[1], l2=[2]", expected: "[1,2]" },
      { input: "l1=[2,5], l2=[1,3,4]", expected: "[1,2,3,4,5]" },
      { input: "l1=[1,1,1], l2=[1,1]", expected: "[1,1,1,1,1]" },
      { input: "l1=[5], l2=[]", expected: "[5]" },
      { input: "l1=[-1,0,3], l2=[-2,4]", expected: "[-2,-1,0,3,4]" },
    ],
    optimalBigO: "O(n+m)",
    optimalSpace: "O(1)",
  },
  {
    title: "Valid Parentheses",
    slug: "valid-parentheses",
    description: "Given a string containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.",
    difficulty: "EASY",
    tags: ["stack", "string"],
    starterCode: {
      python: "def is_valid(s):\n    # TODO\n    return False\n",
      javascript: "function isValid(s) {\n  // TODO\n  return false;\n}\n",
      java: "class Solution {\n    public boolean isValid(String s) {\n        // TODO\n        return false;\n    }\n}\n",
    },
    visibleTests: [
      { input: "s=()", expected: "true" },
      { input: "s=()[]{}", expected: "true" },
      { input: "s=(]", expected: "false" },
    ],
    hiddenTests: [
      { input: "s=([{}])", expected: "true" },
      { input: "s=({[)]}", expected: "false" },
      { input: "s=", expected: "true" },
      { input: "s=((((", expected: "false" },
      { input: "s=[])", expected: "false" },
    ],
    optimalBigO: "O(n)",
    optimalSpace: "O(n)",
  },
  {
    title: "Climbing Stairs",
    slug: "climbing-stairs",
    description: "You are climbing a staircase. It takes n steps to reach the top. Each time you can climb 1 or 2 steps. How many distinct ways can you climb to the top?",
    difficulty: "EASY",
    tags: ["dynamic-programming"],
    starterCode: {
      python: "def climb_stairs(n):\n    # TODO\n    return 0\n",
      javascript: "function climbStairs(n) {\n  // TODO\n  return 0;\n}\n",
      java: "class Solution {\n    public int climbStairs(int n) {\n        // TODO\n        return 0;\n    }\n}\n",
    },
    visibleTests: [
      { input: "n=2", expected: "2" },
      { input: "n=3", expected: "3" },
      { input: "n=5", expected: "8" },
    ],
    hiddenTests: [
      { input: "n=1", expected: "1" },
      { input: "n=10", expected: "89" },
      { input: "n=15", expected: "987" },
      { input: "n=20", expected: "10946" },
      { input: "n=25", expected: "121393" },
    ],
    optimalBigO: "O(n)",
    optimalSpace: "O(1)",
  },
  {
    title: "Best Time to Buy and Sell Stock",
    slug: "best-time-to-buy-and-sell-stock",
    description: "Given an array prices where prices[i] is the price of a given stock on the i-th day, maximize profit with one transaction.",
    difficulty: "EASY",
    tags: ["array", "two-pointers"],
    starterCode: {
      python: "def max_profit(prices):\n    # TODO\n    return 0\n",
      javascript: "function maxProfit(prices) {\n  // TODO\n  return 0;\n}\n",
      java: "class Solution {\n    public int maxProfit(int[] prices) {\n        // TODO\n        return 0;\n    }\n}\n",
    },
    visibleTests: [
      { input: "prices=[7,1,5,3,6,4]", expected: "5" },
      { input: "prices=[7,6,4,3,1]", expected: "0" },
      { input: "prices=[2,4,1]", expected: "2" },
    ],
    hiddenTests: [
      { input: "prices=[1,2]", expected: "1" },
      { input: "prices=[2,1,2,1,0,1,2]", expected: "2" },
      { input: "prices=[3,3,5,0,0,3,1,4]", expected: "4" },
      { input: "prices=[1]", expected: "0" },
      { input: "prices=[2,1,2,1,2]", expected: "1" },
    ],
    optimalBigO: "O(n)",
    optimalSpace: "O(1)",
  },
  {
    title: "Maximum Subarray",
    slug: "maximum-subarray",
    description: "Find the contiguous subarray with the largest sum.",
    difficulty: "EASY",
    tags: ["array", "dynamic-programming"],
    starterCode: {
      python: "def max_sub_array(nums):\n    # TODO\n    return 0\n",
      javascript: "function maxSubArray(nums) {\n  // TODO\n  return 0;\n}\n",
      java: "class Solution {\n    public int maxSubArray(int[] nums) {\n        // TODO\n        return 0;\n    }\n}\n",
    },
    visibleTests: [
      { input: "nums=[-2,1,-3,4,-1,2,1,-5,4]", expected: "6" },
      { input: "nums=[1]", expected: "1" },
      { input: "nums=[5,4,-1,7,8]", expected: "23" },
    ],
    hiddenTests: [
      { input: "nums=[-1,-2,-3]", expected: "-1" },
      { input: "nums=[2,-1,2,3,4,-5]", expected: "10" },
      { input: "nums=[1,-2,3,5,-3,2]", expected: "8" },
      { input: "nums=[-2,-1]", expected: "-1" },
      { input: "nums=[4,-1,2,1]", expected: "6" },
    ],
    optimalBigO: "O(n)",
    optimalSpace: "O(1)",
  },
  {
    title: "Product of Array Except Self",
    slug: "product-of-array-except-self",
    description: "Return an array answer such that answer[i] is the product of all elements of nums except nums[i] without using division.",
    difficulty: "MEDIUM",
    tags: ["array", "prefix"],
    starterCode: {
      python: "def product_except_self(nums):\n    # TODO\n    return []\n",
      javascript: "function productExceptSelf(nums) {\n  // TODO\n  return [];\n}\n",
      java: "class Solution {\n    public int[] productExceptSelf(int[] nums) {\n        // TODO\n        return new int[0];\n    }\n}\n",
    },
    visibleTests: [
      { input: "nums=[1,2,3,4]", expected: "[24,12,8,6]" },
      { input: "nums=[-1,1,0,-3,3]", expected: "[0,0,9,0,0]" },
      { input: "nums=[2,3,4,5]", expected: "[60,40,30,24]" },
    ],
    hiddenTests: [
      { input: "nums=[5,0,5]", expected: "[0,25,0]" },
      { input: "nums=[1,1,1,1]", expected: "[1,1,1,1]" },
      { input: "nums=[9,0,-2]", expected: "[0,-18,0]" },
      { input: "nums=[-2,-2,-2]", expected: "[4,4,4]" },
      { input: "nums=[10]", expected: "[1]" },
    ],
    optimalBigO: "O(n)",
    optimalSpace: "O(1)",
  },
  {
    title: "Sliding Window Maximum",
    slug: "sliding-window-maximum",
    description: "Given an array nums and a window size k, return the maximum for each sliding window.",
    difficulty: "MEDIUM",
    tags: ["deque", "array"],
    starterCode: {
      python: "def max_sliding_window(nums, k):\n    # TODO\n    return []\n",
      javascript: "function maxSlidingWindow(nums, k) {\n  // TODO\n  return [];\n}\n",
      java: "class Solution {\n    public int[] maxSlidingWindow(int[] nums, int k) {\n        // TODO\n        return new int[0];\n    }\n}\n",
    },
    visibleTests: [
      { input: "nums=[1,3,-1,-3,5,3,6,7], k=3", expected: "[3,3,5,5,6,7]" },
      { input: "nums=[1], k=1", expected: "[1]" },
      { input: "nums=[9,10,9,-7,-4,-8,2,-6], k=5", expected: "[10,10,9,2]" },
    ],
    hiddenTests: [
      { input: "nums=[4,3,11], k=3", expected: "[11]" },
      { input: "nums=[7,2,4], k=2", expected: "[7,4]" },
      { input: "nums=[1,3,1,2,0,5], k=3", expected: "[3,3,2,5]" },
      { input: "nums=[-1,-1], k=1", expected: "[-1,-1]" },
      { input: "nums=[2,2,2], k=2", expected: "[2,2]" },
    ],
    optimalBigO: "O(n)",
    optimalSpace: "O(k)",
  },
  {
    title: "Longest Substring Without Repeating Characters",
    slug: "longest-substring-without-repeat",
    description: "Given a string s, find the length of the longest substring without repeating characters.",
    difficulty: "MEDIUM",
    tags: ["sliding-window", "string"],
    starterCode: {
      python: "def length_of_longest_substring(s):\n    # TODO\n    return 0\n",
      javascript: "function lengthOfLongestSubstring(s) {\n  // TODO\n  return 0;\n}\n",
      java: "class Solution {\n    public int lengthOfLongestSubstring(String s) {\n        // TODO\n        return 0;\n    }\n}\n",
    },
    visibleTests: [
      { input: "s=abcabcbb", expected: "3" },
      { input: "s=bbbbb", expected: "1" },
      { input: "s=pwwkew", expected: "3" },
    ],
    hiddenTests: [
      { input: "s=", expected: "0" },
      { input: "s=au", expected: "2" },
      { input: "s=dvdf", expected: "3" },
      { input: "s=tmmzuxt", expected: "5" },
      { input: "s=abba", expected: "2" },
    ],
    optimalBigO: "O(n)",
    optimalSpace: "O(min(n, m))",
  },
  {
    title: "Minimum Window Substring",
    slug: "minimum-window-substring",
    description: "Given two strings s and t, return the minimum window in s which contains all the characters in t.",
    difficulty: "HARD",
    tags: ["sliding-window", "string"],
    starterCode: {
      python: "def min_window(s, t):\n    # TODO\n    return \"\"\n",
      javascript: "function minWindow(s, t) {\n  // TODO\n  return \"\";\n}\n",
      java: "class Solution {\n    public String minWindow(String s, String t) {\n        // TODO\n        return \"\";\n    }\n}\n",
    },
    visibleTests: [
      { input: "s=ADOBECODEBANC, t=ABC", expected: "BANC" },
      { input: "s=a, t=a", expected: "a" },
      { input: "s=a, t=aa", expected: "" },
    ],
    hiddenTests: [
      { input: "s=aa, t=aa", expected: "aa" },
      { input: "s=ab, t=b", expected: "b" },
      { input: "s=ab, t=ab", expected: "ab" },
      { input: "s=ADOBECODEBANC, t=AABC", expected: "ADOBEC" },
      { input: "s=xyyzyzyx, t=xyz", expected: "zyx" },
    ],
    optimalBigO: "O(n)",
    optimalSpace: "O(k)",
  },
  {
    title: "Group Anagrams",
    slug: "group-anagrams",
    description: "Group the anagrams together from an array of strings.",
    difficulty: "MEDIUM",
    tags: ["hash-map", "string"],
    starterCode: {
      python: "def group_anagrams(strs):\n    # TODO\n    return []\n",
      javascript: "function groupAnagrams(strs) {\n  // TODO\n  return [];\n}\n",
      java: "class Solution {\n    public List<List<String>> groupAnagrams(String[] strs) {\n        // TODO\n        return List.of();\n    }\n}\n",
    },
    visibleTests: [
      { input: "strs=[eat, tea, tan, ate, nat, bat]", expected: "[[eat,tea,ate],[tan,nat],[bat]]" },
      { input: "strs=[]", expected: "[]" },
      { input: "strs=[a]", expected: "[[a]]" },
    ],
    hiddenTests: [
      { input: "strs=[abc,bca,cab]", expected: "[[abc,bca,cab]]" },
      { input: "strs=[abc,def]", expected: "[[abc],[def]]" },
      { input: "strs=[, ]", expected: "[[,]]" },
      { input: "strs=[listen,silent,enlist]", expected: "[[listen,silent,enlist]]" },
      { input: "strs=[aaab,abaa,baaa]", expected: "[[aaab,abaa,baaa]]" },
    ],
    optimalBigO: "O(n * m)",
    optimalSpace: "O(n * m)",
  },
  {
    title: "Top K Frequent Elements",
    slug: "top-k-frequent-elements",
    description: "Given an integer array nums and an integer k, return the k most frequent elements.",
    difficulty: "MEDIUM",
    tags: ["heap", "hash-map"],
    starterCode: {
      python: "def top_k_frequent(nums, k):\n    # TODO\n    return []\n",
      javascript: "function topKFrequent(nums, k) {\n  // TODO\n  return [];\n}\n",
      java: "class Solution {\n    public int[] topKFrequent(int[] nums, int k) {\n        // TODO\n        return new int[0];\n    }\n}\n",
    },
    visibleTests: [
      { input: "nums=[1,1,1,2,2,3], k=2", expected: "[1,2]" },
      { input: "nums=[1], k=1", expected: "[1]" },
      { input: "nums=[3,0,1,0], k=1", expected: "[0]" },
    ],
    hiddenTests: [
      { input: "nums=[4,4,4,4], k=1", expected: "[4]" },
      { input: "nums=[1,2,3,4,5,6,6,6], k=2", expected: "[6,1]" },
      { input: "nums=[-1,-1,-2,-2,-3], k=2", expected: "[-1,-2]" },
      { input: "nums=[5,5,5,2,2,3], k=3", expected: "[5,2,3]" },
      { input: "nums=[1,1,2,2,3,3], k=3", expected: "[1,2,3]" },
    ],
    optimalBigO: "O(n log k)",
    optimalSpace: "O(n)",
  },
  {
    title: "Kth Largest Element in Array",
    slug: "kth-largest-element",
    description: "Find the kth largest element in an unsorted array.",
    difficulty: "MEDIUM",
    tags: ["heap", "quickselect"],
    starterCode: {
      python: "def find_kth_largest(nums, k):\n    # TODO\n    return 0\n",
      javascript: "function findKthLargest(nums, k) {\n  // TODO\n  return 0;\n}\n",
      java: "class Solution {\n    public int findKthLargest(int[] nums, int k) {\n        // TODO\n        return 0;\n    }\n}\n",
    },
    visibleTests: [
      { input: "nums=[3,2,1,5,6,4], k=2", expected: "5" },
      { input: "nums=[3,2,3,1,2,4,5,5,6], k=4", expected: "4" },
      { input: "nums=[1], k=1", expected: "1" },
    ],
    hiddenTests: [
      { input: "nums=[7,6,5,4,3,2,1], k=5", expected: "3" },
      { input: "nums=[2,1], k=2", expected: "1" },
      { input: "nums=[-1,-1], k=1", expected: "-1" },
      { input: "nums=[5,2,4,1,3,6,0], k=4", expected: "3" },
      { input: "nums=[2,2,2,2], k=2", expected: "2" },
    ],
    optimalBigO: "O(n)",
    optimalSpace: "O(1)",
  },
  {
    title: "Binary Search",
    slug: "binary-search",
    description: "Given a sorted array of integers and a target, return its index or -1 if not found using binary search.",
    difficulty: "EASY",
    tags: ["binary-search"],
    starterCode: {
      python: "def search(nums, target):\n    # TODO\n    return -1\n",
      javascript: "function search(nums, target) {\n  // TODO\n  return -1;\n}\n",
      java: "class Solution {\n    public int search(int[] nums, int target) {\n        // TODO\n        return -1;\n    }\n}\n",
    },
    visibleTests: [
      { input: "nums=[-1,0,3,5,9,12], target=9", expected: "4" },
      { input: "nums=[-1,0,3,5,9,12], target=2", expected: "-1" },
      { input: "nums=[1], target=0", expected: "-1" },
    ],
    hiddenTests: [
      { input: "nums=[1,2,3,4,5], target=1", expected: "0" },
      { input: "nums=[1,2,3,4,5], target=5", expected: "4" },
      { input: "nums=[1,2,3,4,5], target=3", expected: "2" },
      { input: "nums=[-5,-3,-1], target=-3", expected: "1" },
      { input: "nums=[2,5], target=0", expected: "-1" },
    ],
    optimalBigO: "O(log n)",
    optimalSpace: "O(1)",
  },
  {
    title: "Search in Rotated Sorted Array",
    slug: "search-rotated-sorted-array",
    description: "Search target in a rotated sorted array without duplicates.",
    difficulty: "MEDIUM",
    tags: ["binary-search"],
    starterCode: {
      python: "def search_rotated(nums, target):\n    # TODO\n    return -1\n",
      javascript: "function searchRotated(nums, target) {\n  // TODO\n  return -1;\n}\n",
      java: "class Solution {\n    public int search(int[] nums, int target) {\n        // TODO\n        return -1;\n    }\n}\n",
    },
    visibleTests: [
      { input: "nums=[4,5,6,7,0,1,2], target=0", expected: "4" },
      { input: "nums=[4,5,6,7,0,1,2], target=3", expected: "-1" },
      { input: "nums=[1], target=0", expected: "-1" },
    ],
    hiddenTests: [
      { input: "nums=[5,1,3], target=5", expected: "0" },
      { input: "nums=[5,1,3], target=3", expected: "2" },
      { input: "nums=[6,7,1,2,3,4,5], target=4", expected: "5" },
      { input: "nums=[1,3], target=3", expected: "1" },
      { input: "nums=[3,1], target=1", expected: "1" },
    ],
    optimalBigO: "O(log n)",
    optimalSpace: "O(1)",
  },
  {
    title: "Sqrt(x)",
    slug: "sqrtx",
    description: "Compute and return the integer square root of x.",
    difficulty: "EASY",
    tags: ["binary-search", "math"],
    starterCode: {
      python: "def my_sqrt(x):\n    # TODO\n    return 0\n",
      javascript: "function mySqrt(x) {\n  // TODO\n  return 0;\n}\n",
      java: "class Solution {\n    public int mySqrt(int x) {\n        // TODO\n        return 0;\n    }\n}\n",
    },
    visibleTests: [
      { input: "x=4", expected: "2" },
      { input: "x=8", expected: "2" },
      { input: "x=1", expected: "1" },
    ],
    hiddenTests: [
      { input: "x=0", expected: "0" },
      { input: "x=2147395599", expected: "46339" },
      { input: "x=36", expected: "6" },
      { input: "x=15", expected: "3" },
      { input: "x=9999", expected: "99" },
    ],
    optimalBigO: "O(log n)",
    optimalSpace: "O(1)",
  },
  {
    title: "Flood Fill",
    slug: "flood-fill",
    description: "Perform a flood fill on an image starting from a given pixel.",
    difficulty: "EASY",
    tags: ["dfs", "bfs", "matrix"],
    starterCode: {
      python: "def flood_fill(image, sr, sc, color):\n    # TODO\n    return image\n",
      javascript: "function floodFill(image, sr, sc, color) {\n  // TODO\n  return image;\n}\n",
      java: "class Solution {\n    public int[][] floodFill(int[][] image, int sr, int sc, int color) {\n        // TODO\n        return image;\n    }\n}\n",
    },
    visibleTests: [
      { input: "image=[[1,1,1],[1,1,0],[1,0,1]], sr=1, sc=1, color=2", expected: "[[2,2,2],[2,2,0],[2,0,1]]" },
      { input: "image=[[0,0,0],[0,0,0]], sr=0, sc=0, color=0", expected: "[[0,0,0],[0,0,0]]" },
      { input: "image=[[0,0,0],[0,1,1]], sr=1, sc=1, color=1", expected: "[[0,0,0],[0,1,1]]" },
    ],
    hiddenTests: [
      { input: "image=[[1]], sr=0, sc=0, color=1", expected: "[[1]]" },
      { input: "image=[[1,1,1]], sr=0, sc=1, color=3", expected: "[[3,3,3]]" },
      { input: "image=[[2,2,2],[2,2,2]], sr=0, sc=0, color=2", expected: "[[2,2,2],[2,2,2]]" },
      { input: "image=[[1,2,1],[1,1,0]], sr=0, sc=0, color=2", expected: "[[2,2,2],[2,2,0]]" },
      { input: "image=[[0,1,0],[1,0,1],[0,1,0]], sr=1, sc=1, color=1", expected: "[[0,1,0],[1,1,1],[0,1,0]]" },
    ],
    optimalBigO: "O(n*m)",
    optimalSpace: "O(n*m)",
  },
  {
    title: "Number of Islands",
    slug: "number-of-islands",
    description: "Given a 2D grid map of '1's (land) and '0's (water), count the number of islands.",
    difficulty: "MEDIUM",
    tags: ["dfs", "bfs", "matrix"],
    starterCode: {
      python: "def num_islands(grid):\n    # TODO\n    return 0\n",
      javascript: "function numIslands(grid) {\n  // TODO\n  return 0;\n}\n",
      java: "class Solution {\n    public int numIslands(char[][] grid) {\n        // TODO\n        return 0;\n    }\n}\n",
    },
    visibleTests: [
      { input: "grid=[[1,1,1],[0,1,0],[1,1,1]]", expected: "1" },
      { input: "grid=[[1,1,0,0,0],[1,1,0,0,0],[0,0,1,0,0],[0,0,0,1,1]]", expected: "3" },
      { input: "grid=[[0,0,0],[0,0,0]]", expected: "0" },
    ],
    hiddenTests: [
      { input: "grid=[[1]]", expected: "1" },
      { input: "grid=[[1,0,1,0]]", expected: "2" },
      { input: "grid=[[1,1,1,1,0],[1,1,0,1,0],[1,1,0,0,0],[0,0,0,0,0]]", expected: "1" },
      { input: "grid=[[1,0,1,0,1,0]]", expected: "3" },
      { input: "grid=[[1,1,0,1,1],[1,0,0,0,1],[1,1,1,1,1]]", expected: "1" },
    ],
    optimalBigO: "O(n*m)",
    optimalSpace: "O(n*m)",
  },
  {
    title: "Word Search",
    slug: "word-search",
    description: "Given an m x n grid of characters board and a word, return true if the word exists in the grid.",
    difficulty: "MEDIUM",
    tags: ["backtracking", "matrix"],
    starterCode: {
      python: "def exist(board, word):\n    # TODO\n    return False\n",
      javascript: "function exist(board, word) {\n  // TODO\n  return false;\n}\n",
      java: "class Solution {\n    public boolean exist(char[][] board, String word) {\n        // TODO\n        return false;\n    }\n}\n",
    },
    visibleTests: [
      { input: "board=[[A,B,C,E],[S,F,C,S],[A,D,E,E]], word=ABCCED", expected: "true" },
      { input: "board=[[A,B,C,E],[S,F,C,S],[A,D,E,E]], word=SEE", expected: "true" },
      { input: "board=[[A,B,C,E],[S,F,C,S],[A,D,E,E]], word=ABCB", expected: "false" },
    ],
    hiddenTests: [
      { input: "board=[[A]], word=A", expected: "true" },
      { input: "board=[[A,B],[C,D]], word=ABCD", expected: "false" },
      { input: "board=[[A,B],[C,D]], word=ACDB", expected: "true" },
      { input: "board=[[C,A,A],[A,A,A],[B,C,D]], word=AAB", expected: "true" },
      { input: "board=[[X,Y,Z],[Y,Z,X]], word=XYZ", expected: "true" },
    ],
    optimalBigO: "O(n*m*4^L)",
    optimalSpace: "O(L)",
  },
  {
    title: "Coin Change",
    slug: "coin-change",
    description: "Given coins of different denominations and a total amount, compute the fewest coins needed. Return -1 if not possible.",
    difficulty: "MEDIUM",
    tags: ["dynamic-programming"],
    starterCode: {
      python: "def coin_change(coins, amount):\n    # TODO\n    return 0\n",
      javascript: "function coinChange(coins, amount) {\n  // TODO\n  return 0;\n}\n",
      java: "class Solution {\n    public int coinChange(int[] coins, int amount) {\n        // TODO\n        return 0;\n    }\n}\n",
    },
    visibleTests: [
      { input: "coins=[1,2,5], amount=11", expected: "3" },
      { input: "coins=[2], amount=3", expected: "-1" },
      { input: "coins=[1], amount=0", expected: "0" },
    ],
    hiddenTests: [
      { input: "coins=[1,3,4], amount=6", expected: "2" },
      { input: "coins=[2,5,10,1], amount=27", expected: "4" },
      { input: "coins=[1,2,5], amount=100", expected: "20" },
      { input: "coins=[186,419,83,408], amount=6249", expected: "20" },
      { input: "coins=[3,7,405,436], amount=8839", expected: "25" },
    ],
    optimalBigO: "O(amount * n)",
    optimalSpace: "O(amount)",
  },
  {
    title: "Course Schedule",
    slug: "course-schedule",
    description: "Given the total number of courses and prerequisites, return if you can finish all courses.",
    difficulty: "MEDIUM",
    tags: ["graph", "topological-sort"],
    starterCode: {
      python: "def can_finish(numCourses, prerequisites):\n    # TODO\n    return False\n",
      javascript: "function canFinish(numCourses, prerequisites) {\n  // TODO\n  return false;\n}\n",
      java: "class Solution {\n    public boolean canFinish(int numCourses, int[][] prerequisites) {\n        // TODO\n        return false;\n    }\n}\n",
    },
    visibleTests: [
      { input: "numCourses=2, prerequisites=[[1,0]]", expected: "true" },
      { input: "numCourses=2, prerequisites=[[1,0],[0,1]]", expected: "false" },
      { input: "numCourses=4, prerequisites=[[1,0],[2,1],[3,2]]", expected: "true" },
    ],
    hiddenTests: [
      { input: "numCourses=3, prerequisites=[[1,0],[1,2],[0,2]]", expected: "true" },
      { input: "numCourses=1, prerequisites=[]", expected: "true" },
      { input: "numCourses=3, prerequisites=[[0,1],[0,2],[1,2]]", expected: "true" },
      { input: "numCourses=3, prerequisites=[[0,1],[1,2],[2,0]]", expected: "false" },
      { input: "numCourses=5, prerequisites=[[1,4],[2,4],[3,1],[3,2]]", expected: "true" },
    ],
    optimalBigO: "O(V+E)",
    optimalSpace: "O(V+E)",
  },
  {
    title: "Valid Palindrome",
    slug: "valid-palindrome",
    description: "Given a string, determine if it is a palindrome considering only alphanumeric characters and ignoring cases.",
    difficulty: "EASY",
    tags: ["two-pointers", "string"],
    starterCode: {
      python: "def is_palindrome(s):\n    # TODO\n    return False\n",
      javascript: "function isPalindromeString(s) {\n  // TODO\n  return false;\n}\n",
      java: "class Solution {\n    public boolean isPalindrome(String s) {\n        // TODO\n        return false;\n    }\n}\n",
    },
    visibleTests: [
      { input: "s=A man, a plan, a canal: Panama", expected: "true" },
      { input: "s=race a car", expected: "false" },
      { input: "s=", expected: "true" },
    ],
    hiddenTests: [
      { input: "s=ab@a", expected: "true" },
      { input: "s=Noon", expected: "true" },
      { input: "s=0P", expected: "false" },
      { input: "s=.,", expected: "true" },
      { input: "s=Was it a car or a cat I saw", expected: "true" },
    ],
    optimalBigO: "O(n)",
    optimalSpace: "O(1)",
  },
  {
    title: "Longest Palindromic Substring",
    slug: "longest-palindromic-substring",
    description: "Given a string s, return the longest palindromic substring in s.",
    difficulty: "MEDIUM",
    tags: ["string", "expand-around-center"],
    starterCode: {
      python: "def longest_palindrome(s):\n    # TODO\n    return \"\"\n",
      javascript: "function longestPalindrome(s) {\n  // TODO\n  return \"\";\n}\n",
      java: "class Solution {\n    public String longestPalindrome(String s) {\n        // TODO\n        return \"\";\n    }\n}\n",
    },
    visibleTests: [
      { input: "s=babad", expected: "bab" },
      { input: "s=cbbd", expected: "bb" },
      { input: "s=a", expected: "a" },
    ],
    hiddenTests: [
      { input: "s=ac", expected: "a" },
      { input: "s=forgeeksskeegfor", expected: "geeksskeeg" },
      { input: "s=abb", expected: "bb" },
      { input: "s=anana", expected: "anana" },
      { input: "s=tattarrattat", expected: "tattarrattat" },
    ],
    optimalBigO: "O(n^2)",
    optimalSpace: "O(1)",
  },
  {
    title: "Subsets",
    slug: "subsets",
    description: "Given an integer array nums, return all possible subsets (the power set).",
    difficulty: "MEDIUM",
    tags: ["backtracking"],
    starterCode: {
      python: "def subsets(nums):\n    # TODO\n    return []\n",
      javascript: "function subsets(nums) {\n  // TODO\n  return [];\n}\n",
      java: "class Solution {\n    public List<List<Integer>> subsets(int[] nums) {\n        // TODO\n        return List.of();\n    }\n}\n",
    },
    visibleTests: [
      { input: "nums=[1,2,3]", expected: "[[],[1],[2],[3],[1,2],[1,3],[2,3],[1,2,3]]" },
      { input: "nums=[0]", expected: "[[],[0]]" },
      { input: "nums=[1,2]", expected: "[[],[1],[2],[1,2]]" },
    ],
    hiddenTests: [
      { input: "nums=[]", expected: "[[]]" },
      { input: "nums=[1,2,3,4]", expected: "16 subsets" },
      { input: "nums=[5]", expected: "[[],[5]]" },
      { input: "nums=[1,1]", expected: "[[],[1],[1],[1,1]]" },
      { input: "nums=[9,8,7]", expected: "8 subsets" },
    ],
    optimalBigO: "O(n * 2^n)",
    optimalSpace: "O(n * 2^n)",
  },
  {
    title: "Permutations",
    slug: "permutations",
    description: "Given a collection of distinct integers, return all possible permutations.",
    difficulty: "MEDIUM",
    tags: ["backtracking"],
    starterCode: {
      python: "def permute(nums):\n    # TODO\n    return []\n",
      javascript: "function permute(nums) {\n  // TODO\n  return [];\n}\n",
      java: "class Solution {\n    public List<List<Integer>> permute(int[] nums) {\n        // TODO\n        return List.of();\n    }\n}\n",
    },
    visibleTests: [
      { input: "nums=[1,2,3]", expected: "6 permutations" },
      { input: "nums=[0,1]", expected: "2 permutations" },
      { input: "nums=[1]", expected: "1 permutation" },
    ],
    hiddenTests: [
      { input: "nums=[1,2]", expected: "2 permutations" },
      { input: "nums=[1,2,3,4]", expected: "24 permutations" },
      { input: "nums=[5,6,7]", expected: "6 permutations" },
      { input: "nums=[9]", expected: "1 permutation" },
      { input: "nums=[2,3,2]", expected: "6 permutations with duplicates" },
    ],
    optimalBigO: "O(n * n!)",
    optimalSpace: "O(n * n!)",
  },
  {
    title: "Merge Intervals",
    slug: "merge-intervals",
    description: "Given an array of intervals, merge all overlapping intervals.",
    difficulty: "MEDIUM",
    tags: ["intervals", "sorting"],
    starterCode: {
      python: "def merge(intervals):\n    # TODO\n    return []\n",
      javascript: "function merge(intervals) {\n  // TODO\n  return [];\n}\n",
      java: "class Solution {\n    public int[][] merge(int[][] intervals) {\n        // TODO\n        return new int[0][0];\n    }\n}\n",
    },
    visibleTests: [
      { input: "intervals=[[1,3],[2,6],[8,10],[15,18]]", expected: "[[1,6],[8,10],[15,18]]" },
      { input: "intervals=[[1,4],[4,5]]", expected: "[[1,5]]" },
      { input: "intervals=[[1,4],[0,4]]", expected: "[[0,4]]" },
    ],
    hiddenTests: [
      { input: "intervals=[[1,4],[2,3]]", expected: "[[1,4]]" },
      { input: "intervals=[[1,4],[5,6]]", expected: "[[1,4],[5,6]]" },
      { input: "intervals=[[1,4],[0,2],[3,5]]", expected: "[[0,5]]" },
      { input: "intervals=[[2,3],[4,5],[6,7],[8,9],[1,10]]", expected: "[[1,10]]" },
      { input: "intervals=[[1,4],[0,0]]", expected: "[[0,0],[1,4]]" },
    ],
    optimalBigO: "O(n log n)",
    optimalSpace: "O(n)",
  },
  {
    title: "Meeting Rooms",
    slug: "meeting-rooms",
    description: "Given an array of meeting time intervals consisting of start and end times, determine if a person could attend all meetings.",
    difficulty: "EASY",
    tags: ["intervals", "sorting"],
    starterCode: {
      python: "def can_attend_meetings(intervals):\n    # TODO\n    return False\n",
      javascript: "function canAttendMeetings(intervals) {\n  // TODO\n  return false;\n}\n",
      java: "class Solution {\n    public boolean canAttendMeetings(int[][] intervals) {\n        // TODO\n        return false;\n    }\n}\n",
    },
    visibleTests: [
      { input: "intervals=[[0,30],[5,10],[15,20]]", expected: "false" },
      { input: "intervals=[[7,10],[2,4]]", expected: "true" },
      { input: "intervals=[[1,5],[5,8]]", expected: "true" },
    ],
    hiddenTests: [
      { input: "intervals=[[1,2],[2,3],[3,4]]", expected: "true" },
      { input: "intervals=[[1,4],[2,3]]", expected: "false" },
      { input: "intervals=[[1,10],[2,7],[3,19],[8,12],[10,20],[11,30]]", expected: "false" },
      { input: "intervals=[[0,0]]", expected: "true" },
      { input: "intervals=[[1,1],[1,2]]", expected: "false" },
    ],
    optimalBigO: "O(n log n)",
    optimalSpace: "O(1)",
  },
  {
    title: "Insert Interval",
    slug: "insert-interval",
    description: "Insert a new interval into a set of non-overlapping intervals and merge if necessary.",
    difficulty: "MEDIUM",
    tags: ["intervals", "array"],
    starterCode: {
      python: "def insert(intervals, new_interval):\n    # TODO\n    return []\n",
      javascript: "function insert(intervals, newInterval) {\n  // TODO\n  return [];\n}\n",
      java: "class Solution {\n    public int[][] insert(int[][] intervals, int[] newInterval) {\n        // TODO\n        return new int[0][0];\n    }\n}\n",
    },
    visibleTests: [
      { input: "intervals=[[1,3],[6,9]], newInterval=[2,5]", expected: "[[1,5],[6,9]]" },
      { input: "intervals=[[1,2],[3,5],[6,7],[8,10],[12,16]], newInterval=[4,8]", expected: "[[1,2],[3,10],[12,16]]" },
      { input: "intervals=[], newInterval=[5,7]", expected: "[[5,7]]" },
    ],
    hiddenTests: [
      { input: "intervals=[[1,5]], newInterval=[2,3]", expected: "[[1,5]]" },
      { input: "intervals=[[1,5]], newInterval=[2,7]", expected: "[[1,7]]" },
      { input: "intervals=[[3,5],[12,15]], newInterval=[6,6]", expected: "[[3,5],[6,6],[12,15]]" },
      { input: "intervals=[[1,2],[3,5],[6,7],[8,10],[12,16]], newInterval=[17,19]", expected: "[[1,2],[3,5],[6,7],[8,10],[12,16],[17,19]]" },
      { input: "intervals=[[1,2],[3,5],[6,7],[8,10],[12,16]], newInterval=[0,0]", expected: "[[0,0],[1,2],[3,5],[6,7],[8,10],[12,16]]" },
    ],
    optimalBigO: "O(n)",
    optimalSpace: "O(1)",
  },
];

const variants: SeedQuestionInput[] = baseQuestions.map((q, idx) => ({
  ...q,
  title: `${q.title} II`,
  slug: `${q.slug}-ii`,
  difficulty: q.difficulty === "HARD" ? "HARD" : q.difficulty === "MEDIUM" ? "MEDIUM" : "MEDIUM",
  tags: [...q.tags, "variant"],
  visibleTests: q.visibleTests,
  hiddenTests: q.hiddenTests,
}));

export const seedQuestions: SeedQuestionInput[] = [...baseQuestions, ...variants].slice(0, 50);
